export const buses = [
  // Bhopal – Delhi
  {
    id: 1,
    from: "Bhopal",
    to: "Delhi",
    date: "2025-12-25",
    departureTime: "18:30",
    arrivalTime: "07:00",
    duration: "12h 30m",
    price: 1400,
    operator: "Verma Travels",
    busType: "AC Sleeper",
    seatsLeft: 9,
  },
  {
    id: 2,
    from: "Bhopal",
    to: "Delhi",
    date: "2025-12-25",
    departureTime: "21:00",
    arrivalTime: "09:00",
    duration: "12h 00m",
    price: 1100,
    operator: "Hans Travels",
    busType: "Non-AC Sleeper",
    seatsLeft: 4,
  },

  // Bhopal – Indore
  {
    id: 3,
    from: "Bhopal",
    to: "Indore",
    date: "2025-12-25",
    departureTime: "07:00",
    arrivalTime: "11:00",
    duration: "4h 00m",
    price: 350,
    operator: "Verma Travels",
    busType: "AC Seater",
    seatsLeft: 15,
  },
  {
    id: 4,
    from: "Bhopal",
    to: "Indore",
    date: "2025-12-25",
    departureTime: "15:30",
    arrivalTime: "19:30",
    duration: "4h 00m",
    price: 280,
    operator: "Chartered Bus",
    busType: "Non-AC Seater",
    seatsLeft: 22,
  },

  // Indore – Mumbai
  {
    id: 5,
    from: "Indore",
    to: "Mumbai",
    date: "2025-12-26",
    departureTime: "17:45",
    arrivalTime: "08:00",
    duration: "14h 15m",
    price: 1350,
    operator: "Hans Travels",
    busType: "AC Sleeper",
    seatsLeft: 6,
  },
  {
    id: 6,
    from: "Indore",
    to: "Mumbai",
    date: "2025-12-26",
    departureTime: "20:30",
    arrivalTime: "10:00",
    duration: "13h 30m",
    price: 1150,
    operator: "Verma Travels",
    busType: "Non-AC Sleeper",
    seatsLeft: 11,
  },

  // Delhi – Jaipur
  {
    id: 7,
    from: "Delhi",
    to: "Jaipur",
    date: "2025-12-27",
    departureTime: "06:00",
    arrivalTime: "11:00",
    duration: "5h 00m",
    price: 600,
    operator: "Rajasthan Roadways",
    busType: "Non-AC Seater",
    seatsLeft: 30,
  },
  {
    id: 8,
    from: "Delhi",
    to: "Jaipur",
    date: "2025-12-27",
    departureTime: "22:15",
    arrivalTime: "04:00",
    duration: "5h 45m",
    price: 850,
    operator: "RedBus Partner",
    busType: "AC Sleeper",
    seatsLeft: 7,
  },

  // Mumbai – Goa
  {
    id: 9,
    from: "Mumbai",
    to: "Goa",
    date: "2025-12-28",
    departureTime: "19:00",
    arrivalTime: "07:30",
    duration: "12h 30m",
    price: 1550,
    operator: "VRL Travels",
    busType: "AC Sleeper",
    seatsLeft: 12,
  },
  {
    id: 10,
    from: "Mumbai",
    to: "Goa",
    date: "2025-12-28",
    departureTime: "21:30",
    arrivalTime: "10:00",
    duration: "12h 30m",
    price: 1300,
    operator: "SRS Travels",
    busType: "Non-AC Sleeper",
    seatsLeft: 5,
  },
];
